try:
    raise Exception("Ex")
except Exception as ex:
    print(f"F: {ex}")
